# Generated by Django 2.2.3 on 2020-05-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='paid',
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(max_length=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('paid', models.IntegerField()),
                ('outstanding', models.IntegerField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patients')),
            ],
        ),
    ]
