# Generated by Django 2.2.3 on 2020-05-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200524_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='address',
        ),
    ]
