# Generated by Django 2.2.3 on 2020-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200524_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='consulting_doctor_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patients_medical_report',
            name='medical_reports',
            field=models.FileField(upload_to='./medical_reports/'),
        ),
    ]
