# Generated by Django 2.2.3 on 2020-05-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200524_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='consulting_doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.doctor'),
        ),
    ]
