# Generated by Django 2.2.3 on 2020-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200524_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='consulting_doctor_id',
            field=models.IntegerField(),
        ),
    ]
