# Generated by Django 2.2.3 on 2020-05-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20200524_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='doctor_department',
            field=models.CharField(default='General', max_length=25),
            preserve_default=False,
        ),
    ]
