# Generated by Django 3.0.6 on 2020-05-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_appointments_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=50)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patients')),
            ],
        ),
    ]
