# Generated by Django 3.0.6 on 2020-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_patient_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_notifications',
            name='notification',
            field=models.CharField(max_length=100),
        ),
    ]
