# Generated by Django 2.2.3 on 2020-05-25 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200525_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_notifications',
            name='app_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.appointments'),
            preserve_default=False,
        ),
    ]
