# Generated by Django 2.2.3 on 2020-05-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20200525_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='medicines',
            field=models.CharField(max_length=250),
        ),
    ]
