# Generated by Django 2.2.3 on 2020-05-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20200525_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='consultant_fees',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='other_fees',
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='consultant_fees',
            field=models.IntegerField(default=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='other_fees',
            field=models.IntegerField(default=250),
            preserve_default=False,
        ),
    ]
