# Generated by Django 2.2.3 on 2020-05-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20200525_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patients')),
            ],
        ),
    ]
