# Generated by Django 2.2.3 on 2020-05-25 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
